# Generated by Django 4.2.1 on 2023-05-16 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NovelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('readers_num', models.IntegerField(blank=True, null=True)),
                ('ratings', models.IntegerField(default=5.0)),
                ('overview', models.TextField()),
                ('weekly_featured', models.BooleanField(default=False)),
                ('special_featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('authors', models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(to='searchapp.genre')),
            ],
            options={
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='searchapp.novelmodel')),
            ],
        ),
    ]
