# Generated by Django 4.2.1 on 2023-05-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='readers_num',
            field=models.IntegerField(default=0),
        ),
    ]
